# Generated by Django 5.2 on 2025-05-02 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('survey_date', models.DateField(default=django.utils.timezone.now)),
                ('liked_students', models.BooleanField(default=False)),
                ('liked_location', models.BooleanField(default=False)),
                ('liked_campus', models.BooleanField(default=False)),
                ('liked_atmosphere', models.BooleanField(default=False)),
                ('liked_dorm_rooms', models.BooleanField(default=False)),
                ('liked_sports', models.BooleanField(default=False)),
                ('heard_about', models.CharField(choices=[('friends', 'Friends'), ('television', 'Television'), ('internet', 'Internet'), ('other', 'Other')], max_length=20)),
                ('recommend_likelihood', models.CharField(choices=[('very_likely', 'Very Likely'), ('likely', 'Likely'), ('unlikely', 'Unlikely')], max_length=20)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-survey_date', '-created_at'],
            },
        ),
    ]
